"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 10:05:45.627745
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('worker_heartbeat',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('authoring_mode', sa.String(length=20), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('target_runtime_s', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=10), nullable=False),
    sa.Column('takes_per_shot', sa.Integer(), nullable=False),
    sa.Column('overnight', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('character',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('generation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['generation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_generation_target', ['target_type', 'target_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('uq_generation_one_approved', ['target_type', 'target_id', 'kind'], unique=True, sqlite_where=sa.text("status = 'approved'"), postgresql_where=sa.text("status = 'approved'"))

    op.create_table('scene',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('mood', sa.String(length=200), nullable=False),
    sa.Column('lighting', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('generation_id', sa.String(length=36), nullable=True),
    sa.Column('gpu', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('gpu_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_job_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('scene_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'version')
    )
    with op.batch_alter_table('scene_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_version_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_version_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('gpu_seconds', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_ledger_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_ledger_workspace_id'))

    op.drop_table('usage_ledger')
    with op.batch_alter_table('scene_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_version_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_scene_version_scene_id'))

    op.drop_table('scene_version')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_job_updated_at'))
        batch_op.drop_index('ix_job_status_created')
        batch_op.drop_index(batch_op.f('ix_job_project_id'))

    op.drop_table('job')
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_scene_project_id'))

    op.drop_table('scene')
    with op.batch_alter_table('generation', schema=None) as batch_op:
        batch_op.drop_index('uq_generation_one_approved', sqlite_where=sa.text("status = 'approved'"), postgresql_where=sa.text("status = 'approved'"))
        batch_op.drop_index(batch_op.f('ix_generation_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_generation_updated_at'))
        batch_op.drop_index('ix_generation_target')
        batch_op.drop_index(batch_op.f('ix_generation_project_id'))

    op.drop_table('generation')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_character_project_id'))

    op.drop_table('character')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_project_updated_at'))

    op.drop_table('project')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))

    op.drop_table('membership')
    op.drop_table('workspace')
    op.drop_table('worker_heartbeat')
    op.drop_table('user')
    # ### end Alembic commands ###
