"""LTX-2.3 I2V benchmark against the configured ComfyUI.

    cd backend && uv run python ../scripts/bench_ltx.py --image some.png --only 2s,5s

Writes a markdown table to docs/research/benchmark-ltx.md. The first run is a
warm-up (it pays for loading the 22B checkpoint + Gemma) and is reported separately.
The box is a shared production GPU: keep runs short, and Ctrl+C cancels the prompt.
"""
import argparse
import asyncio
import platform
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.config import get_settings  # noqa: E402
from app.drivers.comfy import exec_seconds  # noqa: E402
from app.drivers.comfy_client import parse_outputs, pick_client  # noqa: E402
from app.workflows import build, frames_for, load  # noqa: E402

OUT_MD = ROOT / "docs" / "research" / "benchmark-ltx.md"

CONFIGS = {
    "2s": {"width": 768, "height": 512, "seconds": 2},
    "5s": {"width": 768, "height": 512, "seconds": 5},
    "10s": {"width": 768, "height": 512, "seconds": 10},
    "5s-720p": {"width": 1280, "height": 704, "seconds": 5},
}
PROMPT = ("A weathered deep-sea diver stands on a boat deck at dawn and slowly turns toward the sea, "
          "wind moves her grey hair, gentle swell, handheld camera. Wind and waves, a gull in the distance.")
FPS = 24.0


async def run_config(client, image_name: str, name: str, cfg: dict, seed: int, save_dir: Path | None) -> dict:
    frames = frames_for(cfg["seconds"], FPS)
    graph, resolved = build("ltx23_i2v", {
        "prompt": PROMPT, "first_image": image_name, "width": cfg["width"], "height": cfg["height"],
        "num_frames": frames, "fps": FPS, "seed": seed, "filename_prefix": f"mixai/bench_{name}",
    })
    tpl = load("ltx23_i2v")
    weights = {tpl.node_id(t): w for t, w in tpl.manifest["progress_weights"].items()}

    stages: dict[str, list[float]] = {}
    t0 = time.monotonic()

    def on_progress(frac, msg):
        # "Sampler 3/8" = real denoising steps; plain "Sampler" ticks also cover the model load
        label = msg.split(" ")[0] + ("/steps" if "/" in msg else "")
        now = time.monotonic() - t0
        stages.setdefault(label, [now, now])[1] = now
        print(f"\r  {name}: {frac:4.0%} {msg[:40]:<40}", end="", flush=True)

    _, entry = await client.run(graph, on_progress, timeout=3600, weights=weights)
    wall = time.monotonic() - t0
    print()
    gpu = exec_seconds(entry) or wall
    sampler = stages.get("Sampler/steps")
    out = next((o for o in parse_outputs(entry) if o.kind == "video"), None)
    if out and save_dir:
        await client.download(out, save_dir / f"bench_{name}.mp4")
    out_seconds = frames / FPS
    return {
        "name": name, "size": f"{cfg['width']}x{cfg['height']}", "frames": frames, "out_s": out_seconds,
        "gpu_s": gpu, "wall_s": wall, "sampler_s": (sampler[1] - sampler[0]) if sampler else None,
        "per_s": gpu / out_seconds,
    }


def fmt(v, digits=1):
    return "–" if v is None else f"{v:.{digits}f}"


def write_md(rows: list[dict], warm: dict | None, server: str, todo: list[str]) -> None:
    lines = [
        "# LTX-2.3 I2V benchmark",
        "",
        f"_Generated by `scripts/bench_ltx.py` on {datetime.now():%Y-%m-%d %H:%M} from {platform.system()}; "
        f"server {server} (RTX 4000 Ada 20 GB, 128 GB RAM, ComfyUI 0.38)._",
        "",
        "Template `ltx23_i2v`: LTX-2.3 22B distilled fp8 checkpoint, Gemma 3 12B fp4 text encoder, "
        "8 distilled steps (manual sigmas, CFG 1), first-frame guide, native LTX-AV audio, "
        "tiled VAE decode, VHS h264 mp4 at 24 fps. Single segment, no upscaler pass.",
        "",
        "- **GPU s** = ComfyUI execution time from the history timestamps (what the worker bills).",
        "- **Wall s** = upload-to-result as the client saw it (adds queueing and transfer).",
        "- **Sampler s** = time between the first and last sampler progress event (denoising only).",
        "- **s / output s** = GPU s divided by clip length.",
        "",
        "| Config | Size | Frames | Clip s | GPU s | Wall s | Sampler s | s / output s | Notes |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    if warm:
        lines.append(
            f"| {warm['name']} (warm-up) | {warm['size']} | {warm['frames']} | {fmt(warm['out_s'])} | {fmt(warm['gpu_s'])} | "
            f"{fmt(warm['wall_s'])} | {fmt(warm['sampler_s'])} | {fmt(warm['per_s'])} | first run; pays model load only if LTX wasn't resident |"
        )
    for r in rows:
        lines.append(
            f"| {r['name']} | {r['size']} | {r['frames']} | {fmt(r['out_s'])} | {fmt(r['gpu_s'])} | {fmt(r['wall_s'])} | "
            f"{fmt(r['sampler_s'])} | {fmt(r['per_s'])} | warm |"
        )
    for name in todo:
        cfg = CONFIGS[name]
        lines.append(f"| {name} | {cfg['width']}x{cfg['height']} | {frames_for(cfg['seconds'], FPS)} | {cfg['seconds']} | "
                     "TODO | | | | not run yet (shared GPU budget) |")
    lines += [
        "",
        "## Reading the numbers",
        "",
        "- Model swaps dominate short clips: whenever another workflow (Z-Image, Qwen edit, someone else's job) "
        "ran in between, the 22B checkpoint and Gemma are reloaded / re-offloaded, which costs far more than "
        "the 8 denoising steps. Batch takes per shot back-to-back to stay warm.",
        "- The 22B fp8 weights don't fit in 20 GB, so ComfyUI keeps part of the model in system RAM. "
        "Fixed costs (text encode, VAE decode, mux) make short clips dearer per output second; check whether "
        "sampler time stays near-linear at 10 s, since attention spans every frame.",
        "",
        "## Next (not in this milestone)",
        "",
        "- 10 s and 720p rows above, plus the x2 spatial-upscaler final pass.",
        "- Long takes: `ltx23_longtake_looping` (LTXVLoopingSampler + multi-prompt + AdaIN) and "
        "`ltx23_extend_chunk` (LTXVExtendSampler from a saved tail latent) templates, benchmarked at 30/60 s.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_MD}")


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True, type=Path, help="first frame (any size; centre-cropped)")
    ap.add_argument("--only", default="2s,5s", help=f"comma list from {', '.join(CONFIGS)}")
    ap.add_argument("--seed", type=int, default=1234)
    ap.add_argument("--no-warmup", action="store_true")
    ap.add_argument("--save", type=Path, help="folder to keep the mp4s in")
    args = ap.parse_args()

    names = [n.strip() for n in args.only.split(",") if n.strip()]
    unknown = [n for n in names if n not in CONFIGS]
    if unknown:
        ap.error(f"unknown config(s): {unknown}")
    if args.save:
        args.save.mkdir(parents=True, exist_ok=True)

    s = get_settings()
    client = await pick_client(s.comfy_urls, s.comfy_auth_token, s.comfy_verify_tls)
    try:
        image_name = await client.upload_image(args.image, name="bench_first.png")
        warm = None
        if not args.no_warmup:
            # different seed, or ComfyUI's cache would make the measured run free
            warm = await run_config(client, image_name, names[0], CONFIGS[names[0]], args.seed + 1, None)
        rows = [await run_config(client, image_name, n, CONFIGS[n], args.seed, args.save) for n in names]
        server = client.base_url
    finally:
        await client.close()

    write_md(rows, warm, server, [n for n in CONFIGS if n not in names])
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
